name: Deploy to chotthanhancut.page.gd

on:
  workflow_dispatch:
  push:
    branches:
      - yody

jobs:
  deploy:
    name: Deploy to chotthanhancut.page.gd
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the latest code from GitHub
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Upload code via FTP
      - name: Deploy to chotthanhancut.page.gd via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/  # For addon domains
          timeout: 86400000
          log-level: standard
